/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import fish.payara.micro.BootstrapException;
import fish.payara.micro.PayaraMicro;

public class App {

    public static void main(String[] args) throws BootstrapException {
        PayaraMicro.getInstance().addDeployment(args[0]).bootStrap();
    }
}
